Air Viewer2: edu.wright.airviewer2.AbstractDocumentCommandWrapper.redo
redo()
boolean edu.wright.airviewer2.AbstractDocumentCommandWrapper.redo () inline
Returns
Definition at line 247 of file AbstractDocumentCommandWrapper.java.
{
         boolean result = false;
         if (0 < redoStack.size()) {
             AbstractDocumentCommand command = redoStack.pop();
             AbstractDocumentCommand reciprocal = command.execute();
             if (null != reciprocal) {
                 reciprocal.setUndoName(command.getUndoName());
                 undoStack.push(reciprocal);
                 result = true;
             }
         }
         return result;
     }
References edu.wright.airviewer2.AbstractDocumentCommandWrapper.AbstractDocumentCommand.execute(), edu.wright.airviewer2.AbstractDocumentCommandWrapper.AbstractDocumentCommand.getUndoName(), and edu.wright.airviewer2.AbstractDocumentCommandWrapper.AbstractDocumentCommand.setUndoName().